### ISSUE TITLE
Consider returning empty object instead of null

### ISSUE THREAD

**Issue by maniator** [benjamingr/js-restructure#1]
Consider returning empty object instead of null so that if someone tries to access an element of a failed parse they don't hit an error trying to get a key from null.

Or have the parser throw some error if there was a "real" error and return the empty object otherwise.

**Comment by benjamingr** [comment]
The reason we return `null` is to act similar to `.exec` which behaves this way. Personally I'd rather throw but I want to do what developers find the least surprising. 

Any ideas how to communicate what we return better?

**Comment by maniator** [comment]
Personally I think that the parser function should throw some sort of an error of what went wrong instead of returning null so that I can structure my code better and always assume that the parser will return with the same type and never with null.

Otherwise when using the parser one has to add on a guard clause which I personally find to be a code smell.

It is all a matter of opinion though.

**Comment by maniator** [comment]
Also _maybe_ returning an object with a `_error` key may work as well instead of throwing an error could work. with that key containing a reason of why it failed etc.

All just random ideas I am throwing out.

**Comment by benjamingr** [comment]
I've decided I'll wait for more user feedback before addressing this.
