### ISSUE TITLE
JavaScript does not gaurantee the order or properties

### ISSUE THREAD

**Issue by greggman** [benjamingr/js-restructure#2]
[Does it?](http://stackoverflow.com/a/5525820/128511)

Maybe put them in an array? Or maybe I'm mis-understanding how the RegExp builder keeps the correct order

**Comment by benjamingr** [comment]
Thanks for the comment, actually it does. What's true is that `for... in` and `Object.keys` do not guarantee iteration order. `Object.getOwnPropertyNames` does. See https://esdiscuss.org/topic/property-ordering-of-enumerate-getownpropertynames for details.
